version: '3.8'

services:
  molninlamning:
    image: patrikrj/molninlamning1:latest
    ports:
      - "8081:8080"
    networks:
      - labb1
    depends_on:
      - MyMemoriesDB

  MyMemoriesDB:
    image: patrikrj/mymemoriesdb:latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123!"
    ports:
      - "1433:1433"
    networks:
      - labb1

networks:
  labb1:
    driver: bridge